version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - mynetwork


networks:
  mynetwork:

volumes:
  postgres_data: